### ISSUE TITLE
[1.19.2] Player model is invisible in 1st person view with Better Combat mode

### ISSUE THREAD

**Issue by KitnaD4** [SiverDX/dragonsurvival_compatibility#6]
Basically the title. I don't know if it's a bug or feature, but player's dragon model is invisible in any state in 1st person view (flying/running/standing/fighting/etc). Player is visible in 3rd person view, including in inventory window.
This only occurs when you have compatibility mod AND Better Combat.

Logs seemingly show no anomalies, but I'll attach them just in case they do.
[latest.log](https://github.com/user-attachments/files/15891716/latest.log)

Mods (all latest versions):
Dragon Survival
Dragon Survival Compatibility
GeckoLib
Better Combat
playerAnimator
Cloth Config API

**Comment by SiverDX** [comment]
It's intentional but you shouldn't really see it anyway other than when you look down with `renderFirstPerson` enabled to my understanding (the model should be visible in all GUIs though)

I changed it here so that it should only happen when you attack and the animation is playing
Not sure if it works correctly for all cases

[dragonsurvival_compatibility-1.19.2-1.1.8-all.zip](https://github.com/user-attachments/files/15893742/dragonsurvival_compatibility-1.19.2-1.1.8-all.zip)

**Comment by KitnaD4** [comment]
Yes, everything works correctly. Thank you.

**Comment by SiverDX** [comment]
fixed in latest release
